name = "splittabs-bot"
main = "src/index.ts"
compatibility_date = "2025-05-05"
workers_dev = true

[triggers]
crons = ["0 18 * * SUN"]

[durable_objects]
bindings = [{ name = "STORE", class_name = "Store" }]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Store"]
